{
 "title": "Insights Results Aggregator",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Consumed Messages & Written Reports",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(consumed_messages[5m])", "legendFormat": "consumed messages" },
    { "expr": "rate(written_reports[5m])", "legendFormat": "written reports" }
   ]
  },
  {
   "title": "Requests Rate By URL",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(url)(rate(api_endpoints_requests[5m]))"
    }
   ]
  },
  {
   "title": "API Response Status Codes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(status_code)(rate(api_endpoints_status_codes[5m]))"
    }
   ]
  },
  {
   "title": "API Response Times",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by(url)(rate(api_endpoints_response_time_sum[5m]) / rate(api_endpoints_response_time_count[5m])) ",
     "legendFormat": "{{url}}"
    }
   ]
  },
  {
   "title": "API Non 200 Status Codes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(status_code)(rate(api_endpoints_status_codes{status_code !~ \"2..\"}[5m]))"
    }
   ]
  },
  {
   "title": "Feedback On Rules",
   "type": "graph",
   "description": "Rate of any feedback left by user on rules",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(feedback_on_rules[5m])" }
   ]
  }
 ]
}